[package]
name = "rust_nes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.3"
lazy_static = "1.4.0"
nes_macro = { path = "nes_macro" }
sdl2 = "*"
rand = "*"
